// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class Books extends Table with TableInfo<Books, BooksData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Books(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> title = GeneratedColumn<String>(
    'title',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> author = GeneratedColumn<String>(
    'author',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> filePath = GeneratedColumn<String>(
    'file_path',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL UNIQUE',
  );
  late final GeneratedColumn<String> coverPath = GeneratedColumn<String>(
    'cover_path',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> importDate = GeneratedColumn<int>(
    'import_date',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> lastReadDate = GeneratedColumn<int>(
    'last_read_date',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> readingProgressChapter = GeneratedColumn<int>(
    'reading_progress_chapter',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> readingProgressOffset =
      GeneratedColumn<double>(
        'reading_progress_offset',
        aliasedName,
        true,
        type: DriftSqlType.double,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    title,
    author,
    filePath,
    coverPath,
    importDate,
    lastReadDate,
    readingProgressChapter,
    readingProgressOffset,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'books';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  BooksData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return BooksData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      title: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}title'],
      )!,
      author: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}author'],
      ),
      filePath: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}file_path'],
      )!,
      coverPath: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}cover_path'],
      ),
      importDate: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}import_date'],
      )!,
      lastReadDate: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}last_read_date'],
      ),
      readingProgressChapter: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}reading_progress_chapter'],
      ),
      readingProgressOffset: attachedDatabase.typeMapping.read(
        DriftSqlType.double,
        data['${effectivePrefix}reading_progress_offset'],
      ),
    );
  }

  @override
  Books createAlias(String alias) {
    return Books(attachedDatabase, alias);
  }

  @override
  bool get dontWriteConstraints => true;
}

class BooksData extends DataClass implements Insertable<BooksData> {
  final int id;
  final String title;
  final String? author;
  final String filePath;
  final String? coverPath;
  final int importDate;
  final int? lastReadDate;
  final int? readingProgressChapter;
  final double? readingProgressOffset;
  const BooksData({
    required this.id,
    required this.title,
    this.author,
    required this.filePath,
    this.coverPath,
    required this.importDate,
    this.lastReadDate,
    this.readingProgressChapter,
    this.readingProgressOffset,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['title'] = Variable<String>(title);
    if (!nullToAbsent || author != null) {
      map['author'] = Variable<String>(author);
    }
    map['file_path'] = Variable<String>(filePath);
    if (!nullToAbsent || coverPath != null) {
      map['cover_path'] = Variable<String>(coverPath);
    }
    map['import_date'] = Variable<int>(importDate);
    if (!nullToAbsent || lastReadDate != null) {
      map['last_read_date'] = Variable<int>(lastReadDate);
    }
    if (!nullToAbsent || readingProgressChapter != null) {
      map['reading_progress_chapter'] = Variable<int>(readingProgressChapter);
    }
    if (!nullToAbsent || readingProgressOffset != null) {
      map['reading_progress_offset'] = Variable<double>(readingProgressOffset);
    }
    return map;
  }

  BooksCompanion toCompanion(bool nullToAbsent) {
    return BooksCompanion(
      id: Value(id),
      title: Value(title),
      author: author == null && nullToAbsent
          ? const Value.absent()
          : Value(author),
      filePath: Value(filePath),
      coverPath: coverPath == null && nullToAbsent
          ? const Value.absent()
          : Value(coverPath),
      importDate: Value(importDate),
      lastReadDate: lastReadDate == null && nullToAbsent
          ? const Value.absent()
          : Value(lastReadDate),
      readingProgressChapter: readingProgressChapter == null && nullToAbsent
          ? const Value.absent()
          : Value(readingProgressChapter),
      readingProgressOffset: readingProgressOffset == null && nullToAbsent
          ? const Value.absent()
          : Value(readingProgressOffset),
    );
  }

  factory BooksData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return BooksData(
      id: serializer.fromJson<int>(json['id']),
      title: serializer.fromJson<String>(json['title']),
      author: serializer.fromJson<String?>(json['author']),
      filePath: serializer.fromJson<String>(json['filePath']),
      coverPath: serializer.fromJson<String?>(json['coverPath']),
      importDate: serializer.fromJson<int>(json['importDate']),
      lastReadDate: serializer.fromJson<int?>(json['lastReadDate']),
      readingProgressChapter: serializer.fromJson<int?>(
        json['readingProgressChapter'],
      ),
      readingProgressOffset: serializer.fromJson<double?>(
        json['readingProgressOffset'],
      ),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'title': serializer.toJson<String>(title),
      'author': serializer.toJson<String?>(author),
      'filePath': serializer.toJson<String>(filePath),
      'coverPath': serializer.toJson<String?>(coverPath),
      'importDate': serializer.toJson<int>(importDate),
      'lastReadDate': serializer.toJson<int?>(lastReadDate),
      'readingProgressChapter': serializer.toJson<int?>(readingProgressChapter),
      'readingProgressOffset': serializer.toJson<double?>(
        readingProgressOffset,
      ),
    };
  }

  BooksData copyWith({
    int? id,
    String? title,
    Value<String?> author = const Value.absent(),
    String? filePath,
    Value<String?> coverPath = const Value.absent(),
    int? importDate,
    Value<int?> lastReadDate = const Value.absent(),
    Value<int?> readingProgressChapter = const Value.absent(),
    Value<double?> readingProgressOffset = const Value.absent(),
  }) => BooksData(
    id: id ?? this.id,
    title: title ?? this.title,
    author: author.present ? author.value : this.author,
    filePath: filePath ?? this.filePath,
    coverPath: coverPath.present ? coverPath.value : this.coverPath,
    importDate: importDate ?? this.importDate,
    lastReadDate: lastReadDate.present ? lastReadDate.value : this.lastReadDate,
    readingProgressChapter: readingProgressChapter.present
        ? readingProgressChapter.value
        : this.readingProgressChapter,
    readingProgressOffset: readingProgressOffset.present
        ? readingProgressOffset.value
        : this.readingProgressOffset,
  );
  BooksData copyWithCompanion(BooksCompanion data) {
    return BooksData(
      id: data.id.present ? data.id.value : this.id,
      title: data.title.present ? data.title.value : this.title,
      author: data.author.present ? data.author.value : this.author,
      filePath: data.filePath.present ? data.filePath.value : this.filePath,
      coverPath: data.coverPath.present ? data.coverPath.value : this.coverPath,
      importDate: data.importDate.present
          ? data.importDate.value
          : this.importDate,
      lastReadDate: data.lastReadDate.present
          ? data.lastReadDate.value
          : this.lastReadDate,
      readingProgressChapter: data.readingProgressChapter.present
          ? data.readingProgressChapter.value
          : this.readingProgressChapter,
      readingProgressOffset: data.readingProgressOffset.present
          ? data.readingProgressOffset.value
          : this.readingProgressOffset,
    );
  }

  @override
  String toString() {
    return (StringBuffer('BooksData(')
          ..write('id: $id, ')
          ..write('title: $title, ')
          ..write('author: $author, ')
          ..write('filePath: $filePath, ')
          ..write('coverPath: $coverPath, ')
          ..write('importDate: $importDate, ')
          ..write('lastReadDate: $lastReadDate, ')
          ..write('readingProgressChapter: $readingProgressChapter, ')
          ..write('readingProgressOffset: $readingProgressOffset')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    title,
    author,
    filePath,
    coverPath,
    importDate,
    lastReadDate,
    readingProgressChapter,
    readingProgressOffset,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is BooksData &&
          other.id == this.id &&
          other.title == this.title &&
          other.author == this.author &&
          other.filePath == this.filePath &&
          other.coverPath == this.coverPath &&
          other.importDate == this.importDate &&
          other.lastReadDate == this.lastReadDate &&
          other.readingProgressChapter == this.readingProgressChapter &&
          other.readingProgressOffset == this.readingProgressOffset);
}

class BooksCompanion extends UpdateCompanion<BooksData> {
  final Value<int> id;
  final Value<String> title;
  final Value<String?> author;
  final Value<String> filePath;
  final Value<String?> coverPath;
  final Value<int> importDate;
  final Value<int?> lastReadDate;
  final Value<int?> readingProgressChapter;
  final Value<double?> readingProgressOffset;
  const BooksCompanion({
    this.id = const Value.absent(),
    this.title = const Value.absent(),
    this.author = const Value.absent(),
    this.filePath = const Value.absent(),
    this.coverPath = const Value.absent(),
    this.importDate = const Value.absent(),
    this.lastReadDate = const Value.absent(),
    this.readingProgressChapter = const Value.absent(),
    this.readingProgressOffset = const Value.absent(),
  });
  BooksCompanion.insert({
    this.id = const Value.absent(),
    required String title,
    this.author = const Value.absent(),
    required String filePath,
    this.coverPath = const Value.absent(),
    required int importDate,
    this.lastReadDate = const Value.absent(),
    this.readingProgressChapter = const Value.absent(),
    this.readingProgressOffset = const Value.absent(),
  }) : title = Value(title),
       filePath = Value(filePath),
       importDate = Value(importDate);
  static Insertable<BooksData> custom({
    Expression<int>? id,
    Expression<String>? title,
    Expression<String>? author,
    Expression<String>? filePath,
    Expression<String>? coverPath,
    Expression<int>? importDate,
    Expression<int>? lastReadDate,
    Expression<int>? readingProgressChapter,
    Expression<double>? readingProgressOffset,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (title != null) 'title': title,
      if (author != null) 'author': author,
      if (filePath != null) 'file_path': filePath,
      if (coverPath != null) 'cover_path': coverPath,
      if (importDate != null) 'import_date': importDate,
      if (lastReadDate != null) 'last_read_date': lastReadDate,
      if (readingProgressChapter != null)
        'reading_progress_chapter': readingProgressChapter,
      if (readingProgressOffset != null)
        'reading_progress_offset': readingProgressOffset,
    });
  }

  BooksCompanion copyWith({
    Value<int>? id,
    Value<String>? title,
    Value<String?>? author,
    Value<String>? filePath,
    Value<String?>? coverPath,
    Value<int>? importDate,
    Value<int?>? lastReadDate,
    Value<int?>? readingProgressChapter,
    Value<double?>? readingProgressOffset,
  }) {
    return BooksCompanion(
      id: id ?? this.id,
      title: title ?? this.title,
      author: author ?? this.author,
      filePath: filePath ?? this.filePath,
      coverPath: coverPath ?? this.coverPath,
      importDate: importDate ?? this.importDate,
      lastReadDate: lastReadDate ?? this.lastReadDate,
      readingProgressChapter:
          readingProgressChapter ?? this.readingProgressChapter,
      readingProgressOffset:
          readingProgressOffset ?? this.readingProgressOffset,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (title.present) {
      map['title'] = Variable<String>(title.value);
    }
    if (author.present) {
      map['author'] = Variable<String>(author.value);
    }
    if (filePath.present) {
      map['file_path'] = Variable<String>(filePath.value);
    }
    if (coverPath.present) {
      map['cover_path'] = Variable<String>(coverPath.value);
    }
    if (importDate.present) {
      map['import_date'] = Variable<int>(importDate.value);
    }
    if (lastReadDate.present) {
      map['last_read_date'] = Variable<int>(lastReadDate.value);
    }
    if (readingProgressChapter.present) {
      map['reading_progress_chapter'] = Variable<int>(
        readingProgressChapter.value,
      );
    }
    if (readingProgressOffset.present) {
      map['reading_progress_offset'] = Variable<double>(
        readingProgressOffset.value,
      );
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('BooksCompanion(')
          ..write('id: $id, ')
          ..write('title: $title, ')
          ..write('author: $author, ')
          ..write('filePath: $filePath, ')
          ..write('coverPath: $coverPath, ')
          ..write('importDate: $importDate, ')
          ..write('lastReadDate: $lastReadDate, ')
          ..write('readingProgressChapter: $readingProgressChapter, ')
          ..write('readingProgressOffset: $readingProgressOffset')
          ..write(')'))
        .toString();
  }
}

class Chapters extends Table with TableInfo<Chapters, ChaptersData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Chapters(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<int> bookId = GeneratedColumn<int>(
    'book_id',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES books(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> orderIndex = GeneratedColumn<int>(
    'order_index',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> title = GeneratedColumn<String>(
    'title',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> blocksJson = GeneratedColumn<String>(
    'blocks_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    bookId,
    orderIndex,
    title,
    blocksJson,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'chapters';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  ChaptersData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return ChaptersData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      bookId: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}book_id'],
      )!,
      orderIndex: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}order_index'],
      )!,
      title: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}title'],
      ),
      blocksJson: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}blocks_json'],
      )!,
    );
  }

  @override
  Chapters createAlias(String alias) {
    return Chapters(attachedDatabase, alias);
  }

  @override
  bool get dontWriteConstraints => true;
}

class ChaptersData extends DataClass implements Insertable<ChaptersData> {
  final int id;
  final int bookId;
  final int orderIndex;
  final String? title;
  final String blocksJson;
  const ChaptersData({
    required this.id,
    required this.bookId,
    required this.orderIndex,
    this.title,
    required this.blocksJson,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['book_id'] = Variable<int>(bookId);
    map['order_index'] = Variable<int>(orderIndex);
    if (!nullToAbsent || title != null) {
      map['title'] = Variable<String>(title);
    }
    map['blocks_json'] = Variable<String>(blocksJson);
    return map;
  }

  ChaptersCompanion toCompanion(bool nullToAbsent) {
    return ChaptersCompanion(
      id: Value(id),
      bookId: Value(bookId),
      orderIndex: Value(orderIndex),
      title: title == null && nullToAbsent
          ? const Value.absent()
          : Value(title),
      blocksJson: Value(blocksJson),
    );
  }

  factory ChaptersData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return ChaptersData(
      id: serializer.fromJson<int>(json['id']),
      bookId: serializer.fromJson<int>(json['bookId']),
      orderIndex: serializer.fromJson<int>(json['orderIndex']),
      title: serializer.fromJson<String?>(json['title']),
      blocksJson: serializer.fromJson<String>(json['blocksJson']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'bookId': serializer.toJson<int>(bookId),
      'orderIndex': serializer.toJson<int>(orderIndex),
      'title': serializer.toJson<String?>(title),
      'blocksJson': serializer.toJson<String>(blocksJson),
    };
  }

  ChaptersData copyWith({
    int? id,
    int? bookId,
    int? orderIndex,
    Value<String?> title = const Value.absent(),
    String? blocksJson,
  }) => ChaptersData(
    id: id ?? this.id,
    bookId: bookId ?? this.bookId,
    orderIndex: orderIndex ?? this.orderIndex,
    title: title.present ? title.value : this.title,
    blocksJson: blocksJson ?? this.blocksJson,
  );
  ChaptersData copyWithCompanion(ChaptersCompanion data) {
    return ChaptersData(
      id: data.id.present ? data.id.value : this.id,
      bookId: data.bookId.present ? data.bookId.value : this.bookId,
      orderIndex: data.orderIndex.present
          ? data.orderIndex.value
          : this.orderIndex,
      title: data.title.present ? data.title.value : this.title,
      blocksJson: data.blocksJson.present
          ? data.blocksJson.value
          : this.blocksJson,
    );
  }

  @override
  String toString() {
    return (StringBuffer('ChaptersData(')
          ..write('id: $id, ')
          ..write('bookId: $bookId, ')
          ..write('orderIndex: $orderIndex, ')
          ..write('title: $title, ')
          ..write('blocksJson: $blocksJson')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, bookId, orderIndex, title, blocksJson);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is ChaptersData &&
          other.id == this.id &&
          other.bookId == this.bookId &&
          other.orderIndex == this.orderIndex &&
          other.title == this.title &&
          other.blocksJson == this.blocksJson);
}

class ChaptersCompanion extends UpdateCompanion<ChaptersData> {
  final Value<int> id;
  final Value<int> bookId;
  final Value<int> orderIndex;
  final Value<String?> title;
  final Value<String> blocksJson;
  const ChaptersCompanion({
    this.id = const Value.absent(),
    this.bookId = const Value.absent(),
    this.orderIndex = const Value.absent(),
    this.title = const Value.absent(),
    this.blocksJson = const Value.absent(),
  });
  ChaptersCompanion.insert({
    this.id = const Value.absent(),
    required int bookId,
    required int orderIndex,
    this.title = const Value.absent(),
    required String blocksJson,
  }) : bookId = Value(bookId),
       orderIndex = Value(orderIndex),
       blocksJson = Value(blocksJson);
  static Insertable<ChaptersData> custom({
    Expression<int>? id,
    Expression<int>? bookId,
    Expression<int>? orderIndex,
    Expression<String>? title,
    Expression<String>? blocksJson,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (bookId != null) 'book_id': bookId,
      if (orderIndex != null) 'order_index': orderIndex,
      if (title != null) 'title': title,
      if (blocksJson != null) 'blocks_json': blocksJson,
    });
  }

  ChaptersCompanion copyWith({
    Value<int>? id,
    Value<int>? bookId,
    Value<int>? orderIndex,
    Value<String?>? title,
    Value<String>? blocksJson,
  }) {
    return ChaptersCompanion(
      id: id ?? this.id,
      bookId: bookId ?? this.bookId,
      orderIndex: orderIndex ?? this.orderIndex,
      title: title ?? this.title,
      blocksJson: blocksJson ?? this.blocksJson,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (bookId.present) {
      map['book_id'] = Variable<int>(bookId.value);
    }
    if (orderIndex.present) {
      map['order_index'] = Variable<int>(orderIndex.value);
    }
    if (title.present) {
      map['title'] = Variable<String>(title.value);
    }
    if (blocksJson.present) {
      map['blocks_json'] = Variable<String>(blocksJson.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('ChaptersCompanion(')
          ..write('id: $id, ')
          ..write('bookId: $bookId, ')
          ..write('orderIndex: $orderIndex, ')
          ..write('title: $title, ')
          ..write('blocksJson: $blocksJson')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV2 extends GeneratedDatabase {
  DatabaseAtV2(QueryExecutor e) : super(e);
  late final Books books = Books(this);
  late final Chapters chapters = Chapters(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [books, chapters];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'books',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('chapters', kind: UpdateKind.delete)],
    ),
  ]);
  @override
  int get schemaVersion => 2;
}
