/// v1 → v2 Drift migration test per D-04.
///
/// This test is hand-authored but uses the generated `GeneratedHelper`
/// (from `schema.dart`) and the `DatabaseAtV1` / `DatabaseAtV2` snapshots
/// produced by `dart run drift_dev schema generate`. `SchemaVerifier`
/// wires the snapshots to the runtime `AppDatabase.migration.onUpgrade`
/// handler so the assertions below exercise the exact `stepByStep`
/// closure from `lib/core/db/app_database.dart`.
///
/// Why hand-authored rather than generated by `drift_dev`:
/// - `drift_dev schema generate` writes a `schema.dart` + `schema_vN.dart`
///   file per version but does NOT emit a round-trip migration test when
///   the source (v1) has zero entities — there is simply nothing to
///   verify with the default `verifySelf` shape.
/// - v1 has zero user tables (see `drift_schemas/drift_schema_v1.json`)
///   so the test asserts what the migration must produce: both tables
///   exist after upgrade, and they can accept representative inserts.
///
/// Mitigates threat T-02-03-03 (Tampering of migration):
/// any future change to the v2 schema that silently drops or renames a
/// column will fail one of the assertions below.
library;

import 'package:drift/drift.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:murmur/core/db/app_database.dart';

import 'schema.dart';

void main() {
  group('v1 → v2 migration (D-04)', () {
    late SchemaVerifier verifier;

    setUpAll(() {
      verifier = SchemaVerifier(GeneratedHelper());
    });

    test('upgrades a v1 database to v2 and both tables become queryable',
        () async {
      // 1. Create an empty v1 database from the generated snapshot.
      final connection = await verifier.startAt(1);

      // 2. Open the real AppDatabase against it — this triggers onUpgrade,
      //    which runs our `stepByStep(from1To2: ...)` handler against the
      //    generated `Schema2` view of the tables.
      final db = AppDatabase(connection);
      try {
        // 3. Validate schema shape matches what `drift_dev schema dump`
        //    recorded for v2. `validateDatabaseSchema` throws if the
        //    runtime schema drifted from `drift_schemas/drift_schema_v2.json`.
        await verifier.migrateAndValidate(db, 2);
      } finally {
        await db.close();
      }
    });

    test('v2 schema accepts representative inserts into books and chapters',
        () async {
      // End-to-end check: after migration, the tables are not just present
      // on disk — they actually accept inserts that match D-05 (books) and
      // D-03 (chapters.blocks_json).
      final connection = await verifier.startAt(1);
      final db = AppDatabase(connection);
      try {
        await verifier.migrateAndValidate(db, 2);

        final bookId = await db.into(db.books).insert(
              BooksCompanion.insert(
                title: 'Migration Smoke Test',
                filePath: '/tmp/migration-smoke.epub',
                importDate: DateTime.utc(2026, 4, 11, 20, 0),
                author: const Value('Test Author'),
              ),
            );
        expect(bookId, greaterThan(0));

        final chapterId = await db.into(db.chapters).insert(
              ChaptersCompanion.insert(
                bookId: bookId,
                orderIndex: 0,
                blocksJson: '[]',
              ),
            );
        expect(chapterId, greaterThan(0));

        // Cascade delete: removing the book must remove its chapter.
        await (db.delete(db.books)..where((b) => b.id.equals(bookId))).go();
        final remaining = await db.select(db.chapters).get();
        expect(remaining, isEmpty,
            reason: 'chapters.book_id ON DELETE CASCADE failed');
      } finally {
        await db.close();
      }
    });
  });
}
